import { Notification } from './notification';

export const Notifications: Notification[] = [
  {
    unread: true,
    name: 'Mark Webber',
    action: 'reacted to your recent post',
    with: 'My first tournament today!',
    when: '1m ago',
    preview: '',
    profilePic: 'avatar-mark-webber',
    photo: '',
    class: 'post',
  },
  {
    unread: true,
    name: 'Angela Gray',
    action: 'followed you',
    with: '',
    when: '5m ago',
    preview: '',
    profilePic: 'avatar-angela-gray',
    photo: '',
    class: '',
  },
  {
    unread: true,
    name: 'Jacob Thompson',
    action: 'has joined your group',
    with: 'Chess Club',
    when: '1 day ago',
    preview: '',
    profilePic: 'avatar-jacob-thompson',
    photo: '',
    class: 'group',
  },
  {
    unread: false,
    name: 'Rizky Hasanuddin',
    action: 'sent you a private message',
    with: '',
    when: '5 days ago',
    preview:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    profilePic: 'avatar-rizky-hasanuddin',
    photo: '',
    class: '',
  },
  {
    unread: false,
    name: 'Kimberly Smith',
    action: 'commented on your picture',
    with: '',
    when: '1 week ago',
    preview: '',
    profilePic: 'avatar-kimberly-smith',
    photo: 'image-chess',
    class: '',
  },
  {
    unread: false,
    name: 'Nathan Peterson',
    action: 'reacted to your recent post',
    with: '5 end-game strategies to increase your win rate',
    when: '2 weeks ago',
    preview: '',
    profilePic: 'avatar-nathan-peterson',
    photo: '',
    class: 'post',
  },
  {
    unread: false,
    name: 'Anna Kim',
    action: 'left the group',
    with: 'Chess Club',
    when: '2 weeks ago',
    preview: '',
    profilePic: 'avatar-anna-kim',
    photo: '',
    class: 'group',
  },
];
